name: kilimolink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  dio: ^5.8.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env